#!/usr/bin/env node
/* Bundles src/ into content-hashed assets at the repo root and rewrites the
 * HTML to point at them.
 *
 * The hash is the point. GitHub Pages serves assets with max-age=600, so a
 * fixed filename means returning visitors can run ten minutes of stale code
 * against fresh markup. A filename that changes with the content makes that
 * impossible, and removes the "remember to bump ?v=N" step that a person will
 * eventually forget.
 *
 * No dependencies: load order is declared here, so bundling is concatenation.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');

// Order matters: these are plain scripts sharing a DL namespace, not modules.
const SCRIPTS = ['util.js', 'device.js', 'protocol.js', 'transfer.js', 'session.js', 'ui.js'];
const HTML = ['index.html', 'updates.html'];

const hash = (text) => crypto.createHash('sha256').update(text).digest('hex').slice(0, 10);
const read = (p) => fs.readFileSync(p, 'utf8');

function banner() {
  const version = JSON.parse(read(path.join(ROOT, 'package.json'))).version;
  return `/* dropline v${version} — built ${new Date().toISOString().slice(0, 10)}\n` +
         `   Generated by build.js. Edit files in src/, not this one. */\n`;
}

function clean(pattern) {
  for (const file of fs.readdirSync(ROOT)) {
    if (pattern.test(file)) fs.unlinkSync(path.join(ROOT, file));
  }
}

function build({ check = false } = {}) {
  const js = banner() + SCRIPTS
    .map((name) => `\n/* ── src/${name} ── */\n${read(path.join(SRC, name))}`)
    .join('\n');
  const css = read(path.join(SRC, 'style.css'));

  const jsName = `dropline.${hash(js)}.js`;
  const cssName = `style.${hash(css)}.css`;

  if (check) {
    const missing = [jsName, cssName].filter((f) => !fs.existsSync(path.join(ROOT, f)));
    const linked = read(path.join(ROOT, 'index.html'));
    const stale = !linked.includes(jsName) || !linked.includes(cssName);
    if (missing.length || stale) {
      console.error('Build output is out of date. Run: npm run build');
      console.error(missing.length ? `  missing: ${missing.join(', ')}` : '  index.html points at older assets');
      process.exit(1);
    }
    console.log(`Build is current (${jsName}, ${cssName})`);
    return;
  }

  clean(/^dropline\.[0-9a-f]+\.js$/);
  clean(/^style\.[0-9a-f]+\.css$/);
  fs.writeFileSync(path.join(ROOT, jsName), js);
  fs.writeFileSync(path.join(ROOT, cssName), css);

  for (const page of HTML) {
    const file = path.join(ROOT, page);
    if (!fs.existsSync(file)) continue;
    const updated = read(file)
      .replace(/(?:dropline(?:\.[0-9a-f]+)?)\.js/g, jsName)
      .replace(/(?:style(?:\.[0-9a-f]+)?)\.css/g, cssName);
    fs.writeFileSync(file, updated);
  }

  const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} KB`;
  console.log(`built ${jsName} (${kb(js)})`);
  console.log(`built ${cssName} (${kb(css)})`);
}

build({ check: process.argv.includes('--check') });
